---
title: Skills
hero_image: images/banner.png
description: s2-skills-cc description
version: 4
listed: false
copyedit: false
last_tested: '2019-08-28'
steps:
- title: Skills Link to Careers in Computing
